security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        api_users:
            memory:
                users:
                    admin: { password: '$argon2i$v=19$m=65536,t=4,p=1$WmNwSVJCWnZLV2x1WE5rNg$n1jMPUS/2VZ69tkxWSAffNXrkGtis/rznalyw+W+MBM', roles: ['ROLE_ADMIN', 'ROLE_SUPER_ADMIN'] }

    encoders:
        # this internal class is used by Symfony to represent in-memory users
        Symfony\Component\Security\Core\User\User: 'auto'

    firewalls:
        login:
            stateless: true
            anonymous: true
            provider: api_users
            json_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # enable the following to restrict api to logged-in users only
        # - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }